### ISSUE TITLE
Uncaught ReferenceError: exports is not defined     at retina.js:12

### ISSUE THREAD

**Issue by umairali** [strues/retinajs#269]
I am trying to add retinajs but I am facing this error

Uncaught ReferenceError: exports is not defined at retina.js:12

I am trying with js file
`<script src="/assets/plugins/retinajs/retina.js"></script>`

**Comment by umairali** [comment]
I am trying with js file 

<script src="<?php echo url("/"); ?>/assets/plugins/retinajs/retina.js"></script>

**Comment by whgandalf** [comment]
Same here!

Do you know what was the last versión working good ?

**Comment by lenardchristopher** [comment]
Same

**Comment by migueldemoura** [comment]
Temp fix: add `var exports={};` to retina.js

**Comment by anderskristo** [comment]
@migueldemoura temp fix makes it work for now.

Seems like it's the same problem as this: http://stackoverflow.com/questions/33294705/gulp-babel-exports-is-not-defined

**Comment by migueldemoura** [comment]
This is a duplicate of #264

**Comment by TsuNut** [comment]
Same here.

**Comment by anderskristo** [comment]
@TsuNut add it above: 

`Object.defineProperty(exports, "__esModule", {
  value: true
});`

on line 11

**Comment by TsuNut** [comment]
@anderskristo 

Thanks! However, I included the fix on line 11 as per instructed. No change. Reverted to 2.0.0, still no change. Wonder if using Gulp and/or concatenating has something to do with my issue?

**Comment by nbelley** [comment]
Beware, adding exports as a variable will make all of your other scripts think you're using node.js, if you're not, many other scripts will fail!
